'use strict';
/* ============================================================
   ONCE HUMAN DEVIANT TRACKER — Static Data
   Edit this file to add/remove built-in deviations and traits.
   Custom additions made in the app UI are stored in localStorage.
   ============================================================ */

const DEVIANT_LIST = [
  "Artisan's Touch","Atomic Lighter","Atomic Snail","Butterfly's Emissary",
  "Buzzy Bee","By-The-Wind","Chefosaurus","Disco Ball","Dr. Teddy","Dreamcatcher",
  "Electric Eel","Enchanting Void","Extradimensional Cat","Festering Gel",
  "Fetch-A-Lot Bunny","Flame Essence","Frog the Leaper","Gingerbread House",
  "Growshroom","Grumpy Bulb","H37","Lethal Rabbit","Logging Beaver",
  "Lonewolf's Whisper","Masonic Pyramid","Mini Feaster","Mini Wonder","Mr. Wish",
  "Nutcracker","Orb Lightning","Paper Doll","Party Animal","Party Monkey",
  "Polar Jelly","Pup Buddy","Pyro","Rain Man","Rebecca","Shattered Maiden",
  "Snow Globe","Snowsprite","Space Turner","Strange Door","The Digby Boy",
  "Upper World Spawn","Voodoo Doll","Wish Box","Zeno-Purifier"
];

// Format: { name, effect, deviants: [] | "ALL", neg: bool }
// Negative traits are prefixed with "⚠ " in name.
const TRAIT_DATA = [
  // ── POSITIVE ──────────────────────────────────────────────
  {name:"A World of Charm",effect:"When the Deviation is dormant and regaining Mood, there is a 10% chance that other Territorial Deviations receive Mood +20.",deviants:["Electric Eel"],neg:false},
  {name:"An Old Hand Knows the Ropes",effect:"Faster mood and deviant power consumption, and working speed +10% for territorial deviants.",deviants:["Chefosaurus","Rain Man","Growshroom","The Digby Boy","Electric Eel","Buzzy Bee"],neg:false},
  {name:"Anti-Burnout",effect:"When the Deviation is dormant and regaining Deviant Power, there is a 20% chance that other Territorial Deviations receive Deviant Power +5.",deviants:"ALL",neg:false},
  {name:"Beast of Burden",effect:"Syncing with it grants Max Load +8.",deviants:["Mini Wonder","Mini Feaster","Butterfly's Emissary"],neg:false},
  {name:"Big Cup",effect:"Limit capacity during Crafting is increased by 20%.",deviants:"ALL",neg:false},
  {name:"Brute Force",effect:"Syncing with it grants Max Load +15, Movement Speed -5%.",deviants:["Mini Feaster"],neg:false},
  {name:"Buy 1 Get 2",effect:"When crafting resources, crafting has a 5% chance to produce 1 extra unit.",deviants:"ALL",neg:false},
  {name:"Byproduct",effect:"When Deviation Activity Score is greater than 90%, there's a 10% chance to increase other Deviations' Deviant Power by 2 points when generating resources.",deviants:["Gingerbread House"],neg:false},
  {name:"Cheer Up 1",effect:"Max Mood +30%, Deviant Power recovery speed -5%.",deviants:["Artisan's Touch","Buzzy Bee","Butterfly's Emissary","Disco Ball","Electric Eel","Enchanting Void","Extradimensional Cat","Frog the Leaper","Flame Essence","Fetch-A-Lot Bunny","Logging Beaver","Mini Feaster","Nutcracker","Polar Jelly","Rain Man","The Digby Boy","Upper World Spawn","Voodoo Doll"],neg:false},
  {name:"Cheer Up 2",effect:"Max Mood +40%, Deviant Power recovery speed -5%.",deviants:["Atomic Lighter","Butterfly's Emissary","Buzzy Bee","Disco Ball","Electric Eel","Flame Essence","Frog the Leaper","Gingerbread House","Growshroom","Logging Beaver","Mini Feaster","Nutcracker","Orb Lightning","Polar Jelly","Voodoo Doll","Zeno-Purifier"],neg:false},
  {name:"Cheer Up 3",effect:"Max Mood +50%, Deviant Power recovery speed -5%.",deviants:["Extradimensional Cat","Festering Gel","Fetch-A-Lot Bunny","Logging Beaver","Mini Feaster","Party Monkey","Polar Jelly","Snow Globe","The Digby Boy","Electric Eel","Lonewolf's Whisper","Pup Buddy","Space Turner"],neg:false},
  {name:"City Folk",effect:"Syncing with it grants Max Load +15 when exploring Settlements.",deviants:["Mini Wonder"],neg:false},
  {name:"Clear Lake",effect:"Deviant Power Recovery Speed +7%.",deviants:["Nutcracker"],neg:false},
  {name:"Come As One",effect:"When Crafting Deviations produce resources, output +1 for every 1 Territory Deviation in the Territory.",deviants:["Frog the Leaper"],neg:false},
  {name:"Collection +1",effect:"There is a 5% chance that crafting output +2, and crafting speed -20%.",deviants:["Orb Lightning"],neg:false},
  {name:"Covert Energy 1",effect:"Max Deviant Power +15%.",deviants:["Extradimensional Cat","Fetch-A-Lot Bunny","Mini Wonder","Paper Doll"],neg:false},
  {name:"Covert Energy 2",effect:"Max Deviant Power +20%.",deviants:["Buzzy Bee","Electric Eel","Gingerbread House","Logging Beaver","Mini Feaster"],neg:false},
  {name:"Covert Energy 3",effect:"Max Deviant Power +25%.",deviants:["Pup Buddy"],neg:false},
  {name:"Covert Energy 4",effect:"Max Deviant Power +30%.",deviants:["Dr. Teddy","Mr. Wish"],neg:false},
  {name:"Covert Energy 5",effect:"Max Deviant Power +35%.",deviants:["Electric Eel"],neg:false},
  {name:"Crack Shot",effect:"Having it fight alongside grants Weapon DMG +5%.",deviants:"ALL",neg:false},
  {name:"Daydreaming - Moon Diamond",effect:"Appearance changed. When recovering Energy while dormant, 20% chance to restore 15 Deviant Power to other Territory Deviations.",deviants:["Extradimensional Cat"],neg:false},
  {name:"Daydreaming - Moonlit Jewels",effect:"Appearance changed. When recovering Energy while dormant, 20% chance to restore 15 Deviant Power to other Territory Deviations.",deviants:["Extradimensional Cat"],neg:false},
  {name:"Devoted Laborer",effect:"Mood and Deviant Power consumption +20% for working Territorial Deviations.",deviants:["Electric Eel"],neg:false},
  {name:"Diamond Duke",effect:"When Territory Deviations are working in the Pollution Zone, there is a 5% chance to not consume Energy.",deviants:["Nutcracker"],neg:false},
  {name:"Dream Wild",effect:"When the Deviation is dormant and regaining Deviant Power, there is a 10% chance that other Territorial Deviations receive Deviant Power +10.",deviants:["Electric Eel"],neg:false},
  {name:"Durability",effect:"Sync with it grants Stamina Consumption -5%.",deviants:["Butterfly's Emissary","Mini Feaster"],neg:false},
  {name:"Efficiency Above All",effect:"Crafting speed +20%, Max Storage Capacity -30%.",deviants:["Atomic Lighter","Disco Ball"],neg:false},
  {name:"Efficiency First",effect:"The resource production interval for Crafting is reduced by 5%.",deviants:["Atomic Snail"],neg:false},
  {name:"Eureka Moment",effect:"When generating resources, Crafting has a 1% chance of producing 10 extra units, but resource production interval +50%.",deviants:["Gingerbread House","Orb Lightning"],neg:false},
  {name:"Feisty Vitality - Deep Purple",effect:"Appearance changed. Gains Mood Recovery Speed +30%.",deviants:["Nutcracker"],neg:false},
  {name:"Gold Speaker - Pure Gold",effect:"Appearance changed. When exploring, chance to bring back additional ores.",deviants:["The Digby Boy"],neg:false},
  {name:"Gilded Oracle",effect:"Territorial Deviations may bring back additional Ores.",deviants:["Electric Eel","Fetch-A-Lot Bunny"],neg:false},
  {name:"Gilded Oracle - Pure Gold",effect:"Appearance changed. When exploring, chance to bring back additional ores.",deviants:["The Digby Boy"],neg:false},
  {name:"Growing Pains 1",effect:"Max Deviant Power +30%, Mood recovery speed -5%.",deviants:["Artisan's Touch","Electric Eel","Enchanting Void","Extradimensional Cat","Fetch-A-Lot Bunny","Flame Essence","Grumpy Bulb","Lethal Rabbit","Mini Feaster","Paper Doll","Polar Jelly","Voodoo Doll"],neg:false},
  {name:"Growing Pains 2",effect:"Max Deviant Power +40%, Mood recovery speed -5%.",deviants:["Butterfly's Emissary","Buzzy Bee","Chefosaurus","Electric Eel","Extradimensional Cat","Festering Gel","Flame Essence","Gingerbread House","Lonewolf's Whisper","Mini Feaster","Mr. Wish","Polar Jelly","The Digby Boy","Voodoo Doll","Zeno-Purifier"],neg:false},
  {name:"Growing Pains 3",effect:"Max Deviant Power +50%, Mood recovery speed -5%.",deviants:["Butterfly's Emissary","Buzzy Bee","Disco Ball","Dr. Teddy","Dreamcatcher","Electric Eel","Enchanting Void","Extradimensional Cat","Gingerbread House","H37","Lonewolf's Whisper","Mini Feaster","Rain Man","Strange Door","Upper World Spawn","Zeno-Purifier"],neg:false},
  {name:"Heartthrob",effect:"When Deviant Power decreases, 10% chance other Territorial Deviations also lose Deviant Power. When dormant and regaining Mood, 10% chance other Territorial Deviations receive Mood +5.",deviants:["Electric Eel","Extradimensional Cat","Logging Beaver","Nutcracker","Rebecca"],neg:false},
  {name:"Heavy and Solid",effect:"Higher load grants higher DMG reduction for torso, up to +15%.",deviants:"ALL",neg:false},
  {name:"Hydrophilic",effect:"When Territory Deviations are resting by water, Energy Recovery Speed +30%.",deviants:["Growshroom"],neg:false},
  {name:"Imperfect Endless Motion - Elegant Purple",effect:"Appearance changed. When activated and working, 20% chance to not consume Deviant Power.",deviants:["Nutcracker"],neg:false},
  {name:"Imperfect Endless Motion",effect:"There is a 10% chance that working does not consume Deviant Power.",deviants:["Logging Beaver"],neg:false},
  {name:"Leftover",effect:"When Activity Score > 20%, 10% chance to increase other Deviations' Deviant Power by 1 when generating resources. Max Storage Capacity -20%.",deviants:"ALL",neg:false},
  {name:"Lighten Your Mind",effect:"Lower Load grants higher DMG Reduction for head, up to +15%.",deviants:"ALL",neg:false},
  {name:"Little Helper",effect:"When Crafting Deviations produce resources, 3% chance to not use up Activity Score.",deviants:["Upper World Spawn"],neg:false},
  {name:"Living Map",effect:"Resource production interval -5% for Territorial Deviations.",deviants:["Electric Eel"],neg:false},
  {name:"Long Distance Runner",effect:"Syncing with it grants Stamina Consumption -20%, Movement Speed -10%.",deviants:["Polar Jelly"],neg:false},
  {name:"Medium Cup",effect:"Max Storage Capacity +10%.",deviants:["Disco Ball"],neg:false},
  {name:"Mineral Talent",effect:"When Crafting Deviations produce resources within Oil Field radius, 20% chance to increase output by 1.",deviants:["Disco Ball"],neg:false},
  {name:"Move More, Live Better",effect:"After this Deviation is synced, recover 1 Deviant Power every 8s while sprinting.",deviants:["Snowsprite"],neg:false},
  {name:"One More Bottle",effect:"When generating resources, crafting has a 2% chance to produce 2 extra units.",deviants:"ALL",neg:false},
  {name:"OnePlus",effect:"When Territory Deviations return with resources, 10% chance to bring back rare crystals. Return time increased.",deviants:["Electric Eel","Extradimensional Cat","The Digby Boy"],neg:false},
  {name:"Optimist 1",effect:"Max Mood +15%.",deviants:["Disco Ball"],neg:false},
  {name:"Optimist 2",effect:"Max Mood +20%.",deviants:["Electric Eel","Frog the Leaper"],neg:false},
  {name:"Optimist 3",effect:"Max Mood +25%.",deviants:["Electric Eel","Strange Door"],neg:false},
  {name:"Optimist 4",effect:"Max Mood +30%.",deviants:["Dr. Teddy","Electric Eel"],neg:false},
  {name:"Optimist 5",effect:"Max Mood +35%.",deviants:["Mini Feaster","Voodoo Doll"],neg:false},
  {name:"Optimism - Extra Large",effect:"Appearance changed. Gains Max Mood +40%.",deviants:["Growshroom"],neg:false},
  {name:"Optimism - Good Fortune",effect:"Appearance changed. Gains Max Mood +40%.",deviants:["Extradimensional Cat"],neg:false},
  {name:"Out of Scratch",effect:"When Crafting Deviations produce resources, 3% chance to not use up Deviant Power.",deviants:"ALL",neg:false},
  {name:"Piece of Cake",effect:"When Crafting Deviations produce resources, 5% chance to not use up Activity Score.",deviants:["Strange Door"],neg:false},
  {name:"Power King",effect:"Syncing with it grants Max Load +25, Movement Speed -5%.",deviants:["Polar Jelly","Zeno-Purifier"],neg:false},
  {name:"Power Rewind 1",effect:"Deviant Power Recovery Speed +5%.",deviants:["Electric Eel","Gingerbread House","Polar Jelly"],neg:false},
  {name:"Power Rewind 2",effect:"Deviant Power Recovery Speed +10%.",deviants:["Electric Eel","Mini Feaster","Space Turner"],neg:false},
  {name:"Power Rewind - Purple",effect:"Appearance changed. Gains Energy Recovery Speed +15%.",deviants:["Nutcracker"],neg:false},
  {name:"Praise the Moon - Starry Night",effect:"Appearance changed. When synced, deal 6% more damage at night. Effect halved during day.",deviants:["Butterfly's Emissary"],neg:false},
  {name:"Praise the Sun - Spring Rose",effect:"Appearance changed. When synced, receive 20% more healing during the day. Effect halved at night.",deviants:["Festering Gel"],neg:false},
  {name:"Psychic Kid",effect:"Having this deviation fight alongside grants Status DMG +5%.",deviants:"ALL",neg:false},
  {name:"Pumpkin Lantern",effect:"Max Deviant Power +10%.",deviants:["Buzzy Bee"],neg:false},
  {name:"Reserved Energy - Twisted Fairy Tale",effect:"Appearance changed. Gains Max Energy +40.",deviants:["Nutcracker"],neg:false},
  {name:"Rewind",effect:"Deviant Power recovery speed +10%.",deviants:"ALL",neg:false},
  {name:"Rise and Shine 1",effect:"Mood recovery speed +5%.",deviants:["Space Turner"],neg:false},
  {name:"Rise and Shine 2",effect:"Mood recovery speed +10%.",deviants:["Space Turner"],neg:false},
  {name:"Rise and Shine 3",effect:"Mood recovery speed +15%.",deviants:["Electric Eel"],neg:false},
  {name:"Rise and Shine 4",effect:"Mood recovery speed +20%.",deviants:["Flame Essence"],neg:false},
  {name:"Rise and Shine 5",effect:"Mood recovery speed +25%.",deviants:["Atomic Lighter","Electric Eel"],neg:false},
  {name:"Run Fast",effect:"Syncing with this deviation grants Movement Speed +5%.",deviants:["Mini Wonder"],neg:false},
  {name:"Save Energy",effect:"Stamina Consumption -10%, Movement Speed -5%.",deviants:["Polar Jelly","Voodoo Doll"],neg:false},
  {name:"Slacking Off",effect:"Mood and Deviant Power consumption speed +5% for working Territorial Deviations.",deviants:["Electric Eel","Extradimensional Cat","Flame Essence","The Digby Boy"],neg:false},
  {name:"Smooth Sheep Rustler",effect:"When Activity Score < 20%, consume other Deviations' Deviant Power by 5 when generating resources.",deviants:["Disco Ball","Pup Buddy","Snow Globe","Space Turner","Strange Door"],neg:false},
  {name:"Snooze Aficionado",effect:"When Mood decreases, 10% chance other Territorial Deviations also lose Mood. When dormant and regaining Deviant Power, 10% chance other Territorial Deviations receive Deviant Power +5.",deviants:["Logging Beaver","Paper Doll","Electric Eel","The Digby Boy"],neg:false},
  {name:"Speed Up",effect:"Resource production interval for Crafting reduced by 10%.",deviants:["Space Turner"],neg:false},
  {name:"Stable Energy - Tin Soldier",effect:"Appearance changed. Gains Max Energy +35.",deviants:["Nutcracker"],neg:false},
  {name:"Stable Energy",effect:"Energy Max Limit increased by 30.",deviants:["Extradimensional Cat","Pup Buddy"],neg:false},
  {name:"Stable Vitality - Golden Era",effect:"Appearance changed. Gains Max Mood +35.",deviants:["Nutcracker"],neg:false},
  {name:"Stable Vitality",effect:"Activity score max limit increased by 30.",deviants:["Electric Eel","Mini Feaster"],neg:false},
  {name:"Stardust Affinity - Ocean Blue",effect:"Appearance changed. When working in Pollution Zone, 30% chance to not consume Mood.",deviants:["Nutcracker"],neg:false},
  {name:"Stardust Affinity",effect:"When Territory Deviations are working in Pollution Zone, 20% chance to not consume Vitality.",deviants:["Electric Eel"],neg:false},
  {name:"Stardust Empowerment",effect:"When Crafting Deviations produce resources within Pollution Zone radius, 20% chance to increase output by 1.",deviants:["Electric Eel","Extradimensional Cat","Fetch-A-Lot Bunny","Gingerbread House"],neg:false},
  {name:"Starry Sky - Marine Star",effect:"Appearance changed. When synced, each reload gives 5% Weapon DMG or 5% Status DMG bonus at random.",deviants:["Festering Gel"],neg:false},
  {name:"Street Rascal",effect:"Syncing with it grants Movement Speed +10% in Settlements.",deviants:["Shattered Maiden","Mini Wonder","Butterfly's Emissary"],neg:false},
  {name:"Sweet Talk - Silver Gentleman",effect:"Appearance changed. When recovering Mood while dormant, 25% chance to restore 10 Mood to other Territory Deviations.",deviants:["Nutcracker"],neg:false},
  {name:"Sweet Talk",effect:"When dormant and regaining Mood, 20% chance other Territorial Deviations receive Mood +5.",deviants:"ALL",neg:false},
  {name:"The Joy of Slacking Off",effect:"10% chance that crafting consumes 0 Mood, crafting speed -20%.",deviants:["Gingerbread House","Atomic Snail"],neg:false},
  {name:"The Last Night",effect:"Resource production interval for Crafting reduced by 15%.",deviants:"ALL",neg:false},
  {name:"The Spirit of the Woods - Alice",effect:"Appearance changed. When exploring, 10% chance to bring back Acid.",deviants:["Fetch-A-Lot Bunny"],neg:false},
  {name:"Toxicologist",effect:"Territorial Deviations may bring back Acid.",deviants:["Electric Eel"],neg:false},
  {name:"Toxicologist - Dark Rebel",effect:"Appearance changed. When exploring, chance to bring back Acid.",deviants:["Fetch-A-Lot Bunny"],neg:false},
  {name:"Toxicologist - Green Touch",effect:"When working in Pollution Zone, 25% chance to not consume Energy.",deviants:["Growshroom"],neg:false},
  {name:"Two-Shift System",effect:"Syncing grants Max Load +16 at daytime and Movement Speed +12% at night.",deviants:["Mr. Wish","Polar Jelly"],neg:false},
  {name:"Unhinged Production",effect:"When Activity Score < 20%, consume other Deviations' Deviant Power by 1 when generating resources to produce 2 extra units.",deviants:"ALL",neg:false},
  {name:"Unplanned Production",effect:"10% chance that crafting consumes 0 Deviant Power, crafting speed -20%.",deviants:["Pup Buddy"],neg:false},
  {name:"Upper Hand",effect:"Whenever Energy drops to 0, automatically consume Vitality to recover Energy.",deviants:["Mini Wonder","Mini Feaster","Electric Eel"],neg:false},
  {name:"Vegetative Calm",effect:"Syncing grants Max Stamina +15, Movement Speed -5%.",deviants:["Festering Gel","Mini Feaster"],neg:false},
  {name:"Voluntary Overtime",effect:"10% chance that working does not consume Mood.",deviants:["Electric Eel"],neg:false},
  {name:"Voluntary Overtime - Prism",effect:"Appearance changed. When activated and working, 15% chance to not consume Mood.",deviants:["The Digby Boy","Electric Eel"],neg:false},
  {name:"Wandering Witch",effect:"Max Deviant Power +10%.",deviants:["Shattered Maiden"],neg:false},
  {name:"Water Dormancy",effect:"When Territory Deviations are resting by water, Vitality Recovery Speed +30%.",deviants:["Electric Eel"],neg:false},
  {name:"Water Dormancy - Heavy Ginger",effect:"Appearance changed. When resting by water, gains Mood Recovery Speed +35%.",deviants:["Extradimensional Cat"],neg:false},
  {name:"Weakspot Master - Glistening Blue",effect:"Appearance changed. When synced, hitting a Weakspot increases Secured by 1 additional point. Cooldown: 3s.",deviants:["Butterfly's Emissary"],neg:false},
  {name:"Wellbeing",effect:"Syncing with this Deviation grants Max Stamina +10.",deviants:["Mini Feaster"],neg:false},
  {name:"Wild Wood Spirit",effect:"When Territorial Deviations bring back resources, 5% chance to bring a deviation flower.",deviants:"ALL",neg:false},
  {name:"Woodland Spirit - Alice",effect:"Appearance changed. When exploring, 10% chance to bring back Acid.",deviants:["Fetch-A-Lot Bunny"],neg:false},
  {name:"Wood Yellow",effect:"Mood Recover Speed +7%.",deviants:["Nutcracker"],neg:false},
  {name:"Workaholic - Lights and Shadows",effect:"Appearance changed. When working, gains Energy and Mood consumption interval +20%.",deviants:["Nutcracker"],neg:false},
  // ── NEGATIVE ──────────────────────────────────────────────
  {name:"⚠ Baffling Behavior",effect:"When Deviant Power decreases, 10% chance other Territorial Deviations also lose Deviant Power.",deviants:["Extradimensional Cat","Growshroom","H37","Electric Eel"],neg:true},
  {name:"⚠ Clumsy",effect:"There is a chance that crafting output -1.",deviants:["Atomic Lighter","Frog the Leaper","Party Animal","Space Turner","Strange Door"],neg:true},
  {name:"⚠ Feeling Blue 1",effect:"Max Activity Score -5%.",deviants:["Atomic Lighter","Buzzy Bee","Logging Beaver","Polar Jelly","Strange Door","Orb Lightning","Butterfly's Emissary","Electric Eel","Enchanting Void","Extradimensional Cat","H37","Pup Buddy","The Digby Boy","Upper World Spawn","Zeno-Purifier"],neg:true},
  {name:"⚠ Feeling Blue 2",effect:"Max Activity Score -10%.",deviants:["Atomic Lighter","Buzzy Bee","Electric Eel","Extradimensional Cat","Frog the Leaper","Gingerbread House","Logging Beaver","Lonewolf's Whisper","Mini Feaster","Orb Lightning","Polar Jelly","Space Turner","Strange Door","Zeno-Purifier"],neg:true},
  {name:"⚠ Feeling Blue 3",effect:"Max Activity Score -15%.",deviants:"ALL",neg:true},
  {name:"⚠ Holding the Team Back",effect:"When Mood decreases, 10% chance other Territorial Deviations also lose Mood.",deviants:["Buzzy Bee","Electric Eel","Extradimensional Cat","Nutcracker","Wish Box"],neg:true},
  {name:"⚠ Lazy",effect:"Crafting Speed -10%.",deviants:["Space Turner","Atomic Snail"],neg:true},
  {name:"⚠ Lazy Bones",effect:"Working speed -5% for Territorial Deviations.",deviants:["Electric Eel","Extradimensional Cat","Fetch-A-Lot Bunny","Flame Essence","Paper Doll"],neg:true},
  {name:"⚠ No Such Thing As a Small Cup",effect:"Max Storage Capacity -10%.",deviants:["Frog the Leaper","Masonic Pyramid","Pup Buddy","Space Turner","Strange Door"],neg:true},
  {name:"⚠ Panovision",effect:"Working speed -10% for Territorial Deviations.",deviants:["Electric Eel"],neg:true},
  {name:"⚠ Sedentary",effect:"Syncing grants Max Load -8 when exploring Settlements.",deviants:["Mini Feaster","Polar Jelly","Pyro","Zeno-Purifier"],neg:true},
  {name:"⚠ Slacking Off (Negative)",effect:"Mood and Deviant Power consumption speed +5% for working Territorial Deviations.",deviants:"ALL",neg:true},
  {name:"⚠ Stay Indoors",effect:"Sync grants Stamina consumption +8% in Settlements.",deviants:["Lonewolf's Whisper","Festering Gel","Zeno-Purifier","Mini Feaster","Voodoo Doll"],neg:true},
  {name:"⚠ Worn-Out 1",effect:"Max Deviant Power -5%.",deviants:["Artisan's Touch","Buzzy Bee","Electric Eel","Extradimensional Cat","Lonewolf's Whisper","Mini Feaster","Party Animal","Pup Buddy","Voodoo Doll","Wish Box"],neg:true},
  {name:"⚠ Worn-Out 2",effect:"Max Deviant Power -10%.",deviants:["Buzzy Bee","By-The-Wind","Disco Ball","Electric Eel","Enchanting Void","Extradimensional Cat","Frog the Leaper","Space Turner","Growshroom","Paper Doll","Polar Jelly","Rain Man","Dreamcatcher","Zeno-Purifier"],neg:true},
  {name:"⚠ Worn-Out 3",effect:"Max Deviant Power -15%.",deviants:"ALL",neg:true},
];
